name: preview_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  fluentui_system_icons: ^1.1.255
  flutter:
    sdk: flutter
  reflect_colors: ^0.0.1
  reflect_ui: ^0.1.0
  storybook_dart: ^0.0.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2
  storybook_dart_generator: ^0.0.3

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Thin.ttf
          weight: 100
        - asset: fonts/Inter-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Inter-Black.ttf
          weight: 900
        - asset: fonts/Inter-BlackItalic.ttf
          weight: 900
          style: italic
    - family: JetBrains Mono
      fonts:
        - asset: fonts/JetBrainsMono-Thin.ttf
          weight: 100
        - asset: fonts/JetBrainsMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/JetBrainsMono-ExtraLight.ttf
          weight: 200
        - asset: fonts/JetBrainsMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/JetBrainsMono-Light.ttf
          weight: 300
        - asset: fonts/JetBrainsMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: fonts/JetBrainsMono-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: fonts/JetBrainsMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: fonts/JetBrainsMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: fonts/JetBrainsMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/JetBrainsMono-ExtraBold.ttf
          weight: 800
        - asset: fonts/JetBrainsMono-ExtraBoldItalic.ttf
          weight: 800
          style: italic
